[package]
name = "http"
version = "1.3.2"
edition = "2024"

[dependencies]
# quinn = { path = "../quinn/quinn" }
# httprs_core = { path = "../core" }
tokio = { version = "=1.49.0", features = ["full"] }
base64 = "=0.22.1"
sha1 = "=0.10.6"
rand = "=0.9.2"
