[package]
name = "http"
version = "1.1.0"
edition = "2024"

[dependencies]
# quinn = { path = "../quinn/quinn" }
# httprs_core = { path = "../core" }
tokio = { version = "=1.49.0", features = ["full"] }
