name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            channel: stable
            target: x86_64-unknown-linux-gnu
            test: true

          - os: windows-latest
            channel: stable
            target: x86_64-pc-windows-msvc
            test: true
          
          - os: ubuntu-latest
            channel: stable
            target: aarch64-unknown-linux-gnu
            test: false

    steps:
    - uses: actions/checkout@v4

    # cmake part
    # - name: Conf cmake
    #   run: cmake -S cxx -B build -DCMAKE_BUILD_TYPE=Debug
    # - name: Build CMake
    #   run: cmake --build build --config Debug

    # rust part
    - name: Add target Rust
      run: rustup target add ${{ matrix.target }}

    - name: Build Rust
      run: cargo +${{ matrix.channel }} build --verbose --release --target ${{ matrix.target }}

    - name: Run tests
      if: matrix.test == true
      run: cargo +${{ matrix.channel }} test --verbose --release --target ${{ matrix.target }}
    
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: httplib-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/
